ENCODER_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
I2C_ENABLE = yes
MCU = RP2040
BOOTLOADER = rp2040



LTO_ENABLE = yes
RGB_MATRIX_ENABLE=yes
RGB_MATRIX_DRIVER = ws2812
RGB_MATRIX_CUSTOM_USER = yes 