#pragma once

// ENCODER
#define ENCODER_A_PINS { GP29 }
#define ENCODER_B_PINS { GP28 }
#define ENCODER_RESOLUTION 4

// OLED - SIMPLES
#define OLED_DISPLAY_128X64
#define OLED_DRIVER SSD1306
#define I2C1_SCL_PIN GP27
#define I2C1_SDA_PIN GP26
#define OLED_TIMEOUT 0

// DEBOUNCE
#define DEBOUNCE 5

#define MATRIX_ROWS 3
#define MATRIX_COLS 3

#define WS2812_BYTE_ORDER WS2812_BYTE_ORDER_RGB 